<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Wave.Domain\Wave.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Out\Java\" />
    <Folder Include="Out\Misc\" />
    <Folder Include="Out\ServerManager\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
